### ISSUE TITLE
Create a new participation repo?

### ISSUE THREAD

**Issue by mksm1228** [STAT547-UBC-2019-20/Discussions#1]
Hello @firasm,

I am reading section 15.4.12 for cm015 and I am confused by the instruction telling me to **"clone your participation repo for STAT 547 and navigate to the week01 folder."** Where can I find my participation repo for STAT547 or is it the same participation repo from STAT545A?

**Comment by firasm** [comment]
Hi @mksm1228,

Sorry about the confusion, it will be a different repo for STAT 547 - I have just updated the instructions a bit to make it clearer (and correct). 

To clone the repo, you will first need to accept it [here](https://classroom.github.com/a/uYT4-Doe)

FYI: We'll go over all this in class this morning, so there's no need to do this beforehand. Thanks for being on top of things!

**Comment by mksm1228** [comment]
@firasm 

Thanks Firas! Currently, I am at a research conference in the states so I am trying to stay on top of things. The link you posted didn't work for me. Could you please resend?

**Comment by firasm** [comment]
hmm - I just tried the link on my demo student account and it worked. Do you get an error message? What do you see when you click it? You should see something like this 

<img width="681" alt="Screen Shot 2020-02-25 at 10 08 27 AM" src="https://user-images.githubusercontent.com/2507459/75274010-e2441b00-57b6-11ea-97b7-3dcf15e35258.png">

**Comment by firasm** [comment]
Ah - believe it or not, it seems that GitHub.com is intermittently down: https://www.githubstatus.com

Try again in a bit

**Comment by firasm** [comment]
hi @mksm1228 looks like you were able to do this now (I can see your participation repo) so I'll close this issue. Feel free to reopen if needed.
