### ISSUE TITLE
Unable to run test_script.R

### ISSUE THREAD

**Issue by mksm1228** [STAT547-UBC-2019-20/Discussions#12]
Hello Firas,

I am unable to run the test_script.R using the terminal. I received an error that says "unexpected '<' in "<". I also tried running it on Rstudio by setting the path using here() and using source() to run the R script but Rstudio cannot find the file. Will be there tomorrow for office hours.

**Comment by firasm** [comment]
thanks @mksm1228, in the meantime could you paste the full output that you see? It might be helpful in debugging. 

Also, the operating system and version?

**Comment by mksm1228** [comment]
**Terminal:**

mksm1228@VCHR-KWON-LAB01  ~/Desktop/STAT547/STAT547-participation-mksm1228-1 (master)
$ rscript test_script.R
Error: unexpected '<' in "<"
Execution halted

**Rstudio:**

Error in source(test_script.R) : object 'test_script.R' not found

Operating system: Windows 10 Enterprise
Version: 1903

**Comment by yuliaUU** [comment]
@mksm1228 
*Terminal*: first set path: to Rscript.exe: it is located in Program Files\R\R-3.6.1\bin. my line of code I ran in terminal:
`PATH C:\Program Files\R\R-3.6.1\bin`
and then I ran:
`cd C:\Users\yulia\Desktop\folder`
and 
`Rscript test_script.R`

*Rstudio terminal*, it means that you are in the wrong working directory: run `here()` and it will tell you which directory you are currently in, if it is not where your script is you will have to first set a new working directory and then run `Rscript test_script.R`

**Comment by firasm** [comment]
I think we resolved this in person right @mksm1228 ?
