### ISSUE TITLE
assignment 1 purrr::map()

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#14]
@firasm 

When assignment1 says to use `purrr::map()`, does this mean using `purrr::map()` literally, or are we allowed to use `purrr::map*()` functions as well?

**Comment by firasm** [comment]
Good question!

Everyone, you should check the PRs on your assignment repos! Last week I added a clarification on exactly this in the instructions. See [here](https://github.com/STAT547-UBC-2019-20/assignment-01-dy-lin/pulls) for your repo.

**Comment by firasm** [comment]
Does this answer your question @dy-lin ? If so feel free to close the issue!

**Comment by dy-lin** [comment]
Yes, thank you! I find it odd that we aren't automatically watching our own repos. I did not get notified about the pull request at all.

**Comment by dy-lin** [comment]
I found this issue regarding the "Watching" GitHub Classroom repos: https://github.com/education/classroom/issues/775

**Comment by firasm** [comment]
Thanks - It seems a PR was added, and merged in, but I can't find the setting to enable it...
