### ISSUE TITLE
GitBash setup help

### ISSUE THREAD

**Issue by HJMcSorley** [STAT547-UBC-2019-20/Discussions#16]
Hi @firasm -- Thanks for your help. 
👍 
Please share link(s) to help me set the path for running R scripts in Git Bash on my Windows system (R terminal is able to run them properly).

Thanks,
Hannah

**Comment by firasm** [comment]
hey @HJMcSorley, the instructions are here: https://ubc-mds.github.io/resources_pages/install_ds_stack_windows/

Please scroll down to the section to the "Rscript" section - there is a whole bunch of other stuff in there that you don't need to do.

**Comment by yuliaUU** [comment]
@HJMcSorley I also posted an answer in one of the issues on how to do it on windows

**Comment by firasm** [comment]
@HJMcSorley is this solved? If yes let's close the issue!
