### ISSUE TITLE
public project repo?

### ISSUE THREAD

**Issue by evelynjulia** [STAT547-UBC-2019-20/Discussions#17]
Hi,
Does our project repo need to be public or private? I thought in class we were told to make it private but then in the notes it says public... I may have just heard wrong in class?

**Comment by firasm** [comment]
hmm - it should be public. 

Did I say it should be private ? If so, I didn't mean to!

The _assignment_ and _participation_ repos are meant to be **private** and the _project_ repos should be **public**.

**Comment by evelynjulia** [comment]
Ah okay. I have changed ours. I think you did say in class it should be private but no matter. It's not a hard fix.

**Comment by dy-lin** [comment]
I also heard private. Now that the repo is public, do we need a specific LICENSE?

**Comment by firasm** [comment]
Yes - you and your partner may choose, but I recommend the [MIT License](https://choosealicense.com/licenses/mit/) if you don't have a preference.

**Comment by dy-lin** [comment]
Something seems to have happened after changing the repository status to public-- it seems that the forks may have been disconnected?

**Comment by yuliaUU** [comment]
@dy-lin , yes, when you made repo public, it unforked it ( check-in your group main repo: the number of forks may show 0)

to solve it, you will need to fork it again: and then create another R project and connect it to your forked repo ( same steps we did  at the beginning of 2nd class)

**Comment by evelynjulia** [comment]
@dy-lin 
Here are the steps that I took to fix the issue when I changed mine:

Go to the main repo (STAT547-UBC-2019-20/<group_name>) and you'll have to click "fork" again... Then you will have a new forked version. (You can delete the old one on GitHub if you want). Get the link for the new forked repo from the "clone or download" button on github.

Then on your laptop, go to the folder where you have all the project stuff saved. In the "terminal" (not the "console") if you type `git remote -v` you can see the URLs for the origin forked repo on GitHub and also the upstream repo which is the main project one. Then you can reset the URL for the forked repo by typing `git remote set-url origin ` and the then URL to the new fork.
