### ISSUE TITLE
Fork detached from master

### ISSUE THREAD

**Issue by luckymeng7** [STAT547-UBC-2019-20/Discussions#18]
Hi @firasm ,

When we set the master repo as public, our private fork repo was detached from the master. Do you know how to re-attach the fork repo back? 

Thanks,
Monica

**Comment by firasm** [comment]
Sigh - hooray for unintended consequences. Sorry about this issue (everyone that's affected by it).

Here's what I was able to find. According to [GitHub](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility):

>If a private repository is made public, each of its private forks is turned into a standalone private repository and becomes the parent of its own new repository network. Private forks are never automatically made public because they could contain sensitive commits that shouldn't be exposed publicly.

This means that you will need to:

- Create a new fork of the public repository
- Warning! Repository names are unique, so the new fork will have a "-01" attached to it. This is annoying, but probably for the better
- Move the directory containing your "old fork" that you locally cloned on your computer
- Clone the new fork locally, [link up your new fork with the upstream repo](https://stat545guidebook.netlify.com/git-workflows.html#part-3-getting-changes-from-upstream) like we did in cm102.
- Proceed as normal

-------------------------

P.S. In case you had changes on your old fork that you had not yet merged into master by sending a PR, you should create a new branch on your new fork, physically copy those changes to the new folder on your computer, commit, push, then send a PR to the project repo and then you'll be all good to go!
