### ISSUE TITLE
Group 5

### ISSUE THREAD

**Issue by iciarfernandez** [STAT547-UBC-2019-20/Discussions#2]
Hey - I'm trying to find my group partner, Hyeongcheol Park. I can't see a github username associated to the name in the people following the STAT547 repo, please get in touch if you're taking the course & thank you!

**Comment by yuliaUU** [comment]
hey! this person might have not attended the class- or there was some issue. I think you can email them through Canvas and ask for all the details:)

**Comment by firasm** [comment]
Hi @sciclic, I've moved you into a different group with @jacobgerlofs - see canvas inbox for a message CC'ing you together.
