### ISSUE TITLE
Assignment errors not appearing on html?

### ISSUE THREAD

**Issue by mksm1228** [STAT547-UBC-2019-20/Discussions#24]
In section 1.1 theres a part that says "# To check you wrote the unit test properly, this code should throw an error"
**output(1)**

But, when I knit it to html, the error does not appear. Is it supposed to be like this?

**Comment by firasm** [comment]
It depends on how you have your code chunk set up in RMarkdown.

This is what I see when I try to knit to html:

![Screen Shot 2020-03-08 at 7 30 45 PM](https://user-images.githubusercontent.com/2507459/76178045-51385100-6173-11ea-87cf-da9cd459067e.png)

To reproduce this behaviour, add `error=TRUE` to your code chunk. This will print out the error message and allow the rest of the document to continue. 

Note: you aren't required to do this, we will be able to tell from your function if it should throw an error or not. We will be talking more about this in Lecture 6 on Thursday (parameterized reports).

**Comment by mksm1228** [comment]
Ok thanks Firas!
