### ISSUE TITLE
M2 - Code Troubleshooting: converting strings to numbers?

### ISSUE THREAD

**Issue by jacobgerlofs** [STAT547-UBC-2019-20/Discussions#25]
Hi @firasm 

I've been having some issues trying to get my code to work for Milestone 2. Our data has survey responses, and most of the data points are not recorded as numbers but as characters or strings. For instance, a cell will read "4 - neither satisfied or dissatisfied" or "7 - extremely satisfied" rather than just "4" or "7". I've been trying to create a function to change all these data points into single numbers. Here's my attempt:
```
fix_likert_1 <- function (df){
  for (i in seq_along(df)){
    if (i == '7 = Extremely satisfied'){
      df[[i]] <- 7
    }
    else if (i == '4 = Neither satisfied nor dissatisfied'){
      df[[i]] <- 4
    }
    else if (i == '1 = Not at all satisfied'){
      df[[i]] <- 1
    }
  }
}
map(survey_data, function(df) fix_likert_1(df))
```
The code runs without an error message but every column just returns "NULL". I'm assuming this has something to do with the values not being numbers but being characters or strings. I also probably don't have the logic quite right with using the purrr package and functional programming.

Can you help me get this to work? It would be much appreciated!

Best,
Jake

**Comment by yuliaUU** [comment]
So you need a function?
I was wondering whether just smth more simple will work ? `substr(df$filname, 0, 1)`

**Comment by firasm** [comment]
@jacobgerlofs I'll try and get to this in more detail tomorrow, but in the meantime let me just point you in the right direction.

There are several ways to do this, but have a look at the [`str_replace`](https://stringr.tidyverse.org/reference/str_replace.html) function from the `stringr` package; it should do what you want it to.

usage:

```
library(stringr)
fruits <- c("one apple", "two pears", "three bananas")
str_replace(fruits, "apple", "jackfruit")
```

The output is...
> [1] "one jackfruit" "two pears"     "three bananas"

**Comment by jacobgerlofs** [comment]
@firasm @yuliaUU Thanks for the quick response!

@firasm I've since tried using the stringr package. Here's where I'm at...
```
#Fix column "work life balance" to contain only numbers.
for (i in 1:length(survey_data$work_life_balance)){
  survey_data$work_life_balance[i] <- str_replace(survey_data$work_life_balance[i], "7 = Extremely satisfied", "7")
}
for (i in 1:length(survey_data$work_life_balance)){
  survey_data$work_life_balance[i] <- str_replace(survey_data$work_life_balance[i], "4 = Neither satisfied nor dissatisfied", "4")
}
for (i in 1:length(survey_data$supervisor_relationship)){
  survey_data$work_life_balance[i] <- str_replace(survey_data$work_life_balance[i], "1 = Not at all satisfied", "1")
}
```
This totally works! (and it only took me a few hours :upside_down_face: :woman_facepalming: :woman_shrugging:) However, I have many more columns, some of them with different scales. I know there should be a better way to do this with a more efficient function but I haven't been able to get it to work.

I've tried things like this, but with no success:
```
fix_likert_1 <- function(x){
  for (i in seq_along(x)){
    x[i] <- str_replace(x[i], "7 = Extremely satisfied", "7")
    x[i] <- str_replace(x[i], "4 = Neither satisfied nor dissatisfied", "4")
    x[i] <- str_replace(x[i], "1 = Not at all satisfied", "1")
  }
}
fix_likert_1(survey_data$work_life_balance)
```
I'm guessing because I can't just write the function to take argument "x" and then try and pass in an entire column as a subset of a dataframe? Let me know if you have a solution!
