### ISSUE TITLE
Merge Conflict Help

### ISSUE THREAD

**Issue by jacobgerlofs** [STAT547-UBC-2019-20/Discussions#26]
Hi @firasm,

I'm trying to merge my branch to our group's master, and have run into merge conflicts that I'm not sure how to resolve. I've attached a photo of our network, hopefully this can help.

It seems as though the branch I'm working on was not pulled from the most recent merge into the master. This doesn't make sense to me, because I had pulled in my partner's changes - after their merge - into my fork, and then branched to continue my work (i.e. the changes that were made as of the last blue line commit and subsequent merge were pulled into my fork. At least, I think they were, I received the changes locally and then worked from there).
The extra little yellow arrow at the end of my commits was an attempt to follow GitHub's steps for resolving merge conflicts, but I'm not sure that it has helped.

Any help would be much appreciated!

Best,
Jake

![github_network_mar9](https://user-images.githubusercontent.com/54858703/76252683-732ee380-6206-11ea-9022-9e2c0053445c.jpg)

**Comment by firasm** [comment]
Hi @jacobgerlofs you can stop by my office in ESB 3144 if you need a hand, but from the network, it looks like after you sent a PR, you didn't pull upstream changes your fork's master.
