### ISSUE TITLE
Assignment 3: Peer Review Groups

### ISSUE THREAD

**Issue by firasm** [STAT547-UBC-2019-20/Discussions#27]
Assignment 3 is a peer review assignment.

Here are the assignments for the group you need to review:

| Student | Group assigned for review |
| ------- | ------------------------- |
| Nima Jamshidi | 8 | 
| Diana Lin | 5 | 
| Rachel Han | 3 | 
| Marion Nyberg | 1 | 
| Sihaoyu Gao | 10 | 
| Martin Keung | 6 | 
| Anh Le | 8 | 
| Eve Wicksteed | 1 | 
| Iciar Fernandez Boyano | 4 | 
| Jake Gerlofs | 7 | 
| Saelin Bjornson | 13 | 
| Carleena Ortega | 9 | 
| Lucy Mosquera | 11 | 
| Denitsa Vasileva | 4 | 
| Jimmy Liu | 2 | 
| Hannah Mcsorley | 13 | 
| Daniel Hadley | 6 | 
| Kristina Wright | 12 | 
| Xuemeng Li | 3 | 
| Stanley Nam | 12 | 
| Almas Khan | 7 | 
| Margot Chen | 2 | 
| Qi Yang | 9 | 
| Racquelle Mangahas | 10 | 
| Farnaz Sahragar | 5 |

**Comment by HJMcSorley** [comment]
@firasm I cannot locate a repo for Group-13 (the group I'm assigned for peer review). Can you assist?

**Comment by firasm** [comment]
@HJMcSorley I've given you access for now, but to fix the underlying issue - @Farnaz1234 and @racquellem you'll need to make your repo public (and re-associate your forks). See [here](https://github.com/STAT547-UBC-2019-20/Discussions/issues/18#issuecomment-595576761) how to do that.

**Comment by yuliaUU** [comment]
@HJMcSorley their group is private: I added

**Comment by HJMcSorley** [comment]
got it thanks
