### ISSUE TITLE
Draft final report for milestone 02

### ISSUE THREAD

**Issue by mksm1228** [STAT547-UBC-2019-20/Discussions#31]
Hello @firasm,

Assignment 3 asks us to look read through the final report but I thought this milestone 2 task was moved to milestone 3? Can I assume that we do not need to see if a draft final report was produced for Assignment 3?

**Comment by firasm** [comment]
Yes - that is a very good point. I guess just make sure the final report (if there is one) compiles? and if it's not there it's N/A.

Thanks!
