### ISSUE TITLE
Class meetings moving online starting Tuesday #flattenthecurve

### ISSUE THREAD

**Issue by firasm** [STAT547-UBC-2019-20/Discussions#32]
Good afternoon @STAT547-UBC-2019-20/students,

Due to the ongoing (legitimate) concerns around limiting the spread of COVID-19, most classes should be moving to online instruction.

This will also apply to STAT 547 - I am still trying to work out the best way to deliver lectures online, but for the meantime, we will (most likely) use zoom.us and I will share my screen - I encourage you to download the app on your computer in preparation. 

In an attempt to reduce stress and account for the additional time it may take for us to learn and apply things (myself included), here's what will change for us:

1. I am extending the grace period for all assignments and milestones by 24h (so the total grace period is 72h from a deadline of Saturday).

2. I will shorten the length of assignments (for A4, A5, A6) by about 25%.

3. For the dashboard project and future milestones, I will scale down expectations to about 80% of what they would have been.

4. I will reduce the amount of material we cover in lectures and instead leave it for additional readings at your leisure.

5. I encourage you all to have virtual meetings rather than meet in person to work on the team projects. However, I understand this may not be easy for everyone to do. So given the current uncertainty with COVID-19, **you may choose to to do the Dashboard projects on your own**. The scope of the project will not be reduced and you will be expected to do all the work yourself. If you would like to do opt for this, please send me a message on Canvas and CC your partner. 

Things are tough right now for many of us, I just want to take a minute to recognize that though many of us are young and healthy, we also have parents, grandparents and others that are amongst the vulnerable population. And even if we don't directly know of someone that could be affected by this - there are still folks all over the world suffering and severely impacted by this. I encourage you to be extra patient, compassionate, considerate, of each other as we work to make the best of the situation.

See you all (virtually) on Tuesday!

P.S. Please **watch** this repo as it will become the primary place we have discussions. 

<img width="159" alt="Screen Shot 2020-03-13 at 3 40 05 PM" src="https://user-images.githubusercontent.com/2507459/76664259-ed31d600-6540-11ea-89a5-0ee648fe61cf.png">

**Comment by Deni678** [comment]
@firasm The extended grace period applies to Milestone 3 as well, right?

**Comment by firasm** [comment]
Yes.

**Comment by Deni678** [comment]
> Yes.

Thank you!

**Comment by dy-lin** [comment]
@firasm are Zoom lectures available for (re-)viewing later on, or are they only live?

**Comment by firasm** [comment]
I will try to record them, and then later post them, but I make no guarantees if this will works and not to mention the quality!
