### ISSUE TITLE
Assignment 4 release

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#33]
@firasm Is it possible to release assignment 4 early as it does not rely on assignment 3 solutions being released?

**Comment by firasm** [comment]
Sure - I'll try and get to it tonight! 

If you'd like to read ahead, we'll be following the multi-step tutorial [here](https://dashr.plot.ly) for the next week and a bit.

**Comment by firasm** [comment]
You can have a look at it [here](https://stat545.stat.ubc.ca/evaluation/assignment_04/assignment_04/). Still working on tweaks it a bit.

**Comment by dy-lin** [comment]
@firasm I see on the [webpage](https://stat545.stat.ubc.ca/evaluation/assignment_04/assignment_04/) it still says:

> THIS ASSIGNMENT IS STILL IN DRAFT FORMAT; will be finalized by Monday evening

Has it been finalized now that it's Tuesday?

**Comment by firasm** [comment]
Yes :-) all good now! I'll take that notice off
