### ISSUE TITLE
Preparing to create Dashboards using Plotly Dash

### ISSUE THREAD

**Issue by firasm** [STAT547-UBC-2019-20/Discussions#35]
Hello @STAT547-UBC-2019-20/students,

In an attempt to reduce technical problems related to system environments, I wanted to send some instructions on how to get your machines setup with the packages and libraries needed to create dashboards. 

Here is a walkthrough:

--------------

## Step 1: Install packages:

First, load the devtools library: 

``` 
library('devtools')
```

In Studio or an R console, install the following packages with the code:

1. All dependencies:

`install.packages(c("fiery", "routr", "reqres", "htmltools", "base64enc", "plotly", "mime", "crayon", "devtools"))`

1. `dash`: `install_github('plotly/dashR', upgrade = TRUE)`
1. `Plotly`: `install.packages('plotly')`

## Step 2: Download [this script](https://github.com/STAT547-UBC-2019-20/Discussions/raw/master/check_dash.R) somewhere on your computer

- Probably good to download it and save it somewhere on your computer
- You can also put it in your participation repo if you like though it's not for marks

## Step 3: Run the script 

- Open a terminal (either in RStudio or in a Terminal on your computer) and run it using:
- Execute this command: `Rscript check_dash.R`

## Step 4: Look for the success message:

> Congratulations! You have successfully installed and loaded all required packages and libraries. You are ready to create Dash apps!

That's it! If you get the message, you'll be ready for Dashboards.

If you do not, you should try to get this figured out before Tuesday. Feel free to open a new issue with your system details (OS, version, R/RStudio version etc...)

**Comment by luckymeng7** [comment]
For anyone who is encountering similar issue as "error: could not find function install_github", remember to send `library("devtools")` in R console before `install_github`

**Comment by dy-lin** [comment]
Using `devtools::install_github()` should work too!

**Comment by firasm** [comment]
Thanks, added that step above!

**Comment by mksm1228** [comment]
Hey @firasm,

Im getting this error when I try to install dash....

HTTP error 403.
  API rate limit exceeded for 172.103.164.95. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2020-03-17 16:22:35 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT

**Comment by yuliaUU** [comment]
@mksm1228 I found the following  on the wed: 
Where similar problem was solved by setting the environmental variable GITHUB_PAT on the repository-settings on travis. For details see https://github.com/forestgeo/learn/issues/148.

And [here](https://github.com/dynverse/dyno/issues/32) they give step by step instructions how to get token and set it as path

**Comment by firasm** [comment]
@mksm1228 You can follow the steps as Yulia describes, but it may be easier to follow the steps from the error message (it will do the same thing in the end):

- Run `usethis::browse_github_pat()` in an R console (it will take you to GitHub.com to authenticate and create a token. once you create it, copy it to clipboard.
- Then run `usethis::edit_r_environ()`  and add the token as `GITHUB_PAT

Let us know if that works!

**Comment by mksm1228** [comment]
@firasm 

Yep it works!
