### ISSUE TITLE
inline R code

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#36]
In milestone 03:

> Be written in Rmarkdown and should not have any “hard-coded” numbers and values
> - Use r code chunks or inline r code)
> -  Load an RDS file from your analysis script and report the relevant results of the statistical analysis

Since only the images from the exploratory data analysis are being added (and R code), is it okay to have values from the exploratory analysis hardcoded?

@firasm

**Comment by firasm** [comment]
Hmmm no, I'd like you to export things as a csv or RDS/RDA file, load it in, and reference it using in-line R code or a code chunk. 

I encourage you NOT to duplicate code between your EDA file and your final report. That way if you make any changes, you'll have to do it in two places.

If you give me an example of what you're trying to include in the report I can give you more specific advice!

**Comment by dy-lin** [comment]
Ahh okay! I was just wondering if the inline R code only applied to the statistical analysis/linear regression or if applied to exploratory data analysis too.
