### ISSUE TITLE
Zoom Meeting details for Tuesday lectures: cm107, cm109, and cm111

### ISSUE THREAD

**Issue by firasm** [STAT547-UBC-2019-20/Discussions#37]
@STAT547-UBC-2019-20/students Below are the Zoom meeting details for Tuesday lectures.

I've started the meeting from 10:30 AM in case you want to arrive a few mins earlier to try things out.

You will need the meeting password (972838)

## Disclaimer

Zoom is hosted on servers in the U.S. This includes recordings done through Zoom.
If you have privacy concerns about your data: a) provide only your first name or a nickname when you join a session and b) keep your camera off and microphone muted.

We will be recording these sessions but the recordings will not be distributed.

## Meeting Details 

Firas Moosvi is inviting you to a scheduled Zoom meeting.

Topic: STAT547-cm107, cm109, cm111
Time: Mar 17, 2020 10:30 AM Vancouver
        Every 7 days, 3 occurrence(s)
        Mar 17, 2020 10:30 AM
        Mar 24, 2020 10:30 AM
        Mar 31, 2020 10:30 AM

Please download and import the following iCalendar (.ics) files to your calendar system.
Daily: https://us04web.zoom.us/meeting/vJcucu6hrzgvgnL_PrZNMFaf3FpLR249gg/ics?icsToken=98tyKuirrT4tE9WWtV_9UbMqA9rlbOHmlHZAhpxtjiXLLgZSZFDQJs5wYOYmF9-B

Join Zoom Meeting
https://us04web.zoom.us/j/133579135?pwd=ODNOazBGSU9Jay9jYi9SNUR1aEMwUT09

Meeting ID: 133 579 135
Password: 972838

One tap mobile
+17789072071,,133579135# Canada
+12045151268,,133579135# Canada

Dial by your location
        +1 778 907 2071 Canada
        +1 204 515 1268 Canada
        +1 438 809 7799 Canada
        +1 587 328 1099 Canada
        +1 647 374 4685 Canada
        +1 647 558 0588 Canada

Meeting ID: 133 579 135
Find your local number: https://us04web.zoom.us/u/fblG2lfgY

**Comment by Nima-Jamshidi** [comment]
Hi Firas,
I have lost the connection to the zoom meeting. I tried again to get in the meeting and it says the host should let me in. Could you please do that?

**Comment by dy-lin** [comment]
@firasm Today's class will me cm108. Are there different Zoom details for today?

**Comment by firasm** [comment]
@dy-lin yes, thanks - just posted in #42

**Comment by firasm** [comment]
@STAT547-UBC-2019-20/students : Zoom link for today's class is above! let me know if things don't work.

**Comment by HJMcSorley** [comment]
Hi @firasm The link to zoom tells me "The host has another meeting in progress"

**Comment by firasm** [comment]
Hmm - that's odd - a few people are already in the zoom session.

**Comment by dy-lin** [comment]
I was able to get in using the Meeting ID and password (didn't try the link though)

**Comment by firasm** [comment]
I just tried this link on my phone and it worked: https://us04web.zoom.us/j/133579135?pwd=ODNOazBGSU9Jay9jYi9SNUR1aEMwUT09

**Comment by HJMcSorley** [comment]
Thanks @dy-lin, I got in with the password and code 👍

**Comment by almas2019** [comment]
Hi Firas,
I can't join the meeting either. it says meeting in progress

On Mar. 24, 2020 10:59 a.m., Firas Moosvi <notifications@github.com> wrote:

I just tried this link on my phone and it worked: https://us04web.zoom.us/j/133579135?pwd=ODNOazBGSU9Jay9jYi9SNUR1aEMwUT09

**Comment by yuliaUU** [comment]
You the log in info (the one with code and password)
