### ISSUE TITLE
Cannot update the app.R file online

### ISSUE THREAD

**Issue by luckymeng7** [STAT547-UBC-2019-20/Discussions#38]
Hi Firas,

At the end of my app.R file, I used "app$run_server(debug = TRUE)" to be able to modify the app.R when the rscript is running. However, I still have the error to save the file as "The process cannot access the file because it is being used by another process"

Do you know where could possibly be wrong on my system?

Thanks,
Monica

**Comment by firasm** [comment]
Hmm - could it be you have another RStudio session open with `Rscript app.R` running there? Or perhaps a terminal? 

I suggest restarting RStudio and if that doesn't fix it, then your computer.

**Comment by yuliaUU** [comment]
Or may be you did not press save to save app.R?

**Comment by luckymeng7** [comment]
Thanks for the replies. However, I power cycled my laptop and it was still the same, the error message showed up when I hit `ctrl + s` or `save`. Should I modify the code after I do `Rscript app.R` and before `ctrl +c` ?

**Comment by firasm** [comment]
yes, assuming you have debug=TRUE, you can launch the app (Rscript app.R), then update the app.R file, and it will show you the recycle emoji and the text in cyan, and then update.

<img width="1777" alt="Screen Shot 2020-03-17 at 3 39 39 PM" src="https://user-images.githubusercontent.com/2507459/76908281-86c0f680-6865-11ea-91a4-01de845f4101.png">

Can you take a screenshot of what you see?

**Comment by luckymeng7** [comment]
Hi Firas, 

Here is the screenshot of what I see after I add a `!` to app.R and trying to save the file
![image](https://user-images.githubusercontent.com/19479517/76923598-17f99280-6891-11ea-8aec-741d168fe000.png)

Thanks

**Comment by firasm** [comment]
Could you see if [this response](https://community.rstudio.com/t/error-saving-script-files/5509/2?u=firas_moosvi) is of any help? 

Are your files on Dropbox or a sync drive?

> Edit: Ah! I think I know why. It's to do with the project folder being backed up to the cloud (Dropbox in this case but I suspect it wouldn't matter which cloud service). The process cannot access the file because it is being used by another process
> 
> I think RStudio is trying to keep my R history or .Rproj file auto-saved for me and this is not playing nicely with Dropbox.

**Comment by luckymeng7** [comment]
Right, this might be an issue. I have it on my dropbox and I did see this often not only editing it online for dash. 

But sadly, when I pause the dropbox sync and move this single script to my desktop, it's still not working... 

![image](https://user-images.githubusercontent.com/19479517/76928836-df14ea00-689f-11ea-9a81-ef54e3ec5272.png)

**Comment by firasm** [comment]
I imagine you restarted RStudio and R ?

Can you try running that from the command prompt or gitbash/powershell ?That might lead to a whole host of other problems.

I guess the workaround is to remove debug=TRUE and Ctrl+C and re-run every time you want to update the app? This is frustrating sorry! Maybe in office hours on Thursday I can have another look at it.

**Comment by luckymeng7** [comment]
Hi Firas, 

I tried to run it from my PowerShell and but it was still showing the same error message if I edit the file in Rstudio. However, if I modify the script in Notepad++, the updating works when running in both Rstudio and PowerShell. 

Looks like there might be some platform issue in my Rstudio. Thanks for your help!

**Comment by yuliaUU** [comment]
Hi!I had that issue too: on my computer, the following steps helped  1. go to terminal and press ctrl+C; 2. `rscript app.R` and then run the `rstudioapi::viewer("http://127.0.0.1:8050") in console`

**Comment by firasm** [comment]
Okay, I'd try updating RStudio and see if that solves the issue

**Comment by firasm** [comment]
@Nima-Jamshidi was also having this issue. Let me know if it's resolved or if you found a workaround. I wasn't able to find anything concrete about it online...

**Comment by firasm** [comment]
@Nima-Jamshidi I think Yulia said she solved your issue today - could you share the solution so @luckymeng7 can also apply it ?

**Comment by yuliaUU** [comment]
@luckymeng7  if you want, we can have a short zoom call!

**Comment by Nima-Jamshidi** [comment]
@firasm Yes, thankfully @yuliaUU showed a way around the problem. I just wanted to try it again before sharing it with @luckymeng7 that I found even an easier and more straightforward solution. 
@yuliaUU 's solution: On the main rscript (app.R), next to the save button (on the ribbon that you usually find the knit button) there is a "Source on Save" option that you need to check. Afterward, all you need to do is to select all the script and hit run (with `debug=TRUE`). Now you can change your script without halting the process. After a change, you just need to save the script as usual.

The new way that I found: In your Console use source function to run your script (with `debug=TRUE`). like this: 

`source('C:/participation/cm110/app.R')'

No need to check "Source on Save" anymore.

**Comment by yuliaUU** [comment]
But I thought Sourve you have to press everytime you want to reload the app. While source on save automatically reload the app after you press save button to save the changes written in the script.

**Comment by Nima-Jamshidi** [comment]
Not based on a few tries I have done so far. 
What I found is that the Source on Save approach behaves a little odd, especially if I change sth on another file that is sourced in the main file. Sometimes hitting Save on the secondary file would prompt the software to show the modification on the html page. But sometimes I need to stop the console and after that console would rerun the script by itself again and show the change.
But so far based on my tries, source() approach has worked without the mentioned problem above.

**Comment by yuliaUU** [comment]
Oh! Interesting! Will try it on mine tomorrow!

**Comment by luckymeng7** [comment]
Hi @yuliaUU and @Nima-Jamshidi ,

Thanks for sharing your solutions. I tried to check "source on save", unfortunately, it's not working for me. Let me know if I missed anything. And I'm good to call anytime after 8pm today.

My current workaround is to use Notepad++ to modify the script while keep the script running in Rscript or powershell.

**Comment by yuliaUU** [comment]
@luckymeng7  are you available for a quick zoom call at 12pm?

**Comment by luckymeng7** [comment]
Hi @yuliaUU , 

Sorry that I missed your message. Actually "Source on save" somewhat helped.  I could update the script if I source the app.R in console upon save, rather then calling it in my terminal. 
 
![image](https://user-images.githubusercontent.com/19479517/77835244-0f625100-7108-11ea-8158-6d0dac418bc2.png)


Thanks,
Monica
