### ISSUE TITLE
makefile repeats outputs

### ISSUE THREAD

**Issue by carleenaortega** [STAT547-UBC-2019-20/Discussions#39]
running make all repeats the EDA and the knit based on the number of targets. We've tried running just one target but it also runs all the other targets in that script..how can we get around this?

**Comment by firasm** [comment]
Can you point me to your Makefile ? I'll try to have a look at it tonight

**Comment by mksm1228** [comment]
@firasm 

@Sihaoyu1220 and I were also having the same problem when we type in ```make all``` in the terminal...

https://github.com/STAT547-UBC-2019-20/group_3_mksm1228_sihaoyu1220/blob/master/Makefile

**Comment by carleenaortega** [comment]
Hi @firasm, here's the link to our makefile: https://github.com/STAT547-UBC-2019-20/group_06/blob/master/Milestone_3/Makefile

Thanks!

**Comment by yuliaUU** [comment]
what happens if you switch all and clean? will it still run twice?

**Comment by yuliaUU** [comment]
you can also try;
`all : foo.pdf foo.html
    echo All files are now up to date

clean: ....

%.html : %.Rmd
    Rscript -e 'rmarkdown::render("$<")'

%.pdf : %.Rmd
    Rscript -e 'rmarkdown::render("$<")'`

**Comment by matthewconnell** [comment]
@carleenaortega 

I got yours to work without repeating by specifying the folder for each file. For example, you had 

`all : final_report.html final_report.pdf`

I changed it to 

`all : docs/final_report.html docs/final_report.pdf`

but for every file and it seemed to work. Let me know if that helps.

**Comment by mksm1228** [comment]
Hi, 

We have written the make all command in the format @matthewconnell suggested, but the makefile still appears to be downloading the .csv data 3 times. Are there any other fixes?

**Comment by firasm** [comment]
Hi @mksm1228 - for your group's makefile, it looks like you have the .csv files specified as targets for three separate rules (line 18, 22, and 30).

Is that intentional? if so, they will get downloaded each time

<img width="549" alt="Screen Shot 2020-03-21 at 11 16 48 PM" src="https://user-images.githubusercontent.com/2507459/77243677-1221eb00-6bca-11ea-8e81-0b48881a5c6e.png">

**Comment by carleenaortega** [comment]
I did @matthewconnell's suggestion and it worked! Thank you!!

**Comment by firasm** [comment]
How about you @mksm1228 ? Is your issue solved too ?

**Comment by mksm1228** [comment]
Yep resolved! Thanks!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
