### ISSUE TITLE
milestone04 clarification

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#40]
> The next part of your project requires you to create a dashboard for your dataset. You need to make a proposal for a dashboard and it should have two components:
> 1. Dashboard description and usage scenarios (~ **300 words**)
>2. Dashboard sketch

vs.

> If necessary, you should consider revising your research question(s) based on the feedback of your peers, and so it is appropriate for a dashboard. Then, consider how the dashboard can be used to answer your research question(s) by a fictional person - these are usage scenarios. Building from your research questions, give a high-level description of the interface for the app you will build. Remember to be realistic about your expectations and plans since you will actually be implementing this app next week and the week after. All of this content should be approximately **200 words** and live in the main project `README.md` file of your GitHub.com repository.

Which word count is it?

Additionally, I cannot view the example sketch on the [webpage](https://stat545.stat.ubc.ca/evaluation/milestone_04/milestone_04/).

**Comment by firasm** [comment]
Thanks - It's 300 words!

I bumped it up to give you some extra space but keep in mind this is just an estimate.

Fixed appSketch

![AppSketch](https://user-images.githubusercontent.com/2507459/77034437-3fbb2a00-6967-11ea-810a-8ae70151691b.png)

**Comment by dy-lin** [comment]
Is it 300 words for Description, and 300 for usage scenario? or 300 combined?

**Comment by firasm** [comment]
300 combined - again rough guideline so if you need a bit more, that's fine.
