### ISSUE TITLE
Assignment 4 clarification

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#41]
> ## Task 2.2 - Add a Markdown component (you can still fill it with random text from here) (5 points)
> - [ ] Add a markdown component that includes the following things:
> - [ ] Add a link
> - [ ] Add some bolded text
> - [ ] Add some italic text
> - [ ] Add a static image referencing an image in your repo or a URL (make sure you have permission to use the image).

When you say 'add a markdown component', does this mean we can only use one single `dccMarkdown()` all together, or can we put each (link, bolded, italic, etc) in multiple separate `dccMarkdown()` calls in the list?

**Comment by yuliaUU** [comment]
I think what it means is : you can borrow a *text* from that [link given]() , you can then  apply different **markdown features** like I show in my example in my reply

## You  can do it wherever you want or how you want 

> but I will appreciate that it will be obvious for TAs to spot them in one document!

**Comment by firasm** [comment]
Hey @dy-lin ,

Ideally one dccMarkdown component with all those features but I guess it doesn’t really matter as long as you demonstrate proficiency with the markdown component.
