### ISSUE TITLE
Zoom Meeting Details for cm108 and cm110 and cm112 (Thursdays)

### ISSUE THREAD

**Issue by firasm** [STAT547-UBC-2019-20/Discussions#42]
Hi @STAT547-UBC-2019-20/students, 

## Disclaimer

Zoom is hosted on servers in the U.S. This includes recordings done through Zoom.
If you have privacy concerns about your data: a) provide only your first name or a nickname when you join a session and b) keep your camera off and microphone muted.
We will be recording these sessions but the recordings will not be distributed.

## Meeting info

here are the zoom meeting details for cm108 (today) and cm110 (next thursday)

Firas Moosvi is inviting you to a scheduled Zoom meeting.

Topic: STAT547-cm108 and 110 and 112
Time: This is a recurring meeting Meet anytime

Join Zoom Meeting
https://zoom.us/j/247176733?pwd=ZEFsVmJ4MDRHcmZNQkIwbTZTVVlOdz09

Meeting ID: 247 176 733
Password: 038324

One tap mobile
+19292056099,,247176733# US (New York)
+12532158782,,247176733# US

Dial by your location
        +1 929 205 6099 US (New York)
        +1 253 215 8782 US
        +1 301 715 8592 US
        +1 312 626 6799 US (Chicago)
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
Meeting ID: 247 176 733
Find your local number: https://zoom.us/u/abpM39VaGL

**Comment by firasm** [comment]
@STAT547-UBC-2019-20/students : Today's Zoom meeting details above.

**Comment by almas2019** [comment]
@firasm  I can't join the meeting with the link or the meeting id/password

**Comment by yuliaUU** [comment]
Join Zoom Meeting
https://us04web.zoom.us/j/133579135?pwd=ODNOazBGSU9Jay9jYi9SNUR1aEMwUT09
