### ISSUE TITLE
assignment 4 static image ?

### ISSUE THREAD

**Issue by evelynjulia** [STAT547-UBC-2019-20/Discussions#45]
Hi, could you please send a link / resource where we can learn how to embed a static image for assignment 4? We haven't covered this is class and I can't seem to find info online about how to do it.

**Comment by firasm** [comment]
Oh sure, here are some instructions:

## Method 1

1. Add an image to a folder called `img`, say `test.png`

2. To add the image you need to add this code:

```
![optional_name](img/test.png)
```
## Method 2 (for more control over width and height)

1. Add an image to a folder called `img`, say `test.png`

2. To add the image, use a standard HTML tag:

```
<img src="img/test.png" width="50%">
```
Other options [shown here](http://zevross.com/blog/2017/06/19/tips-and-tricks-for-working-with-images-and-figures-in-r-markdown-documents/)

**Comment by jimmyliu1326** [comment]
@firasm 

Method 1 didn't seem to work for me. I have created a `images` directory with `image.jpg` and in my `app.R`, I added the following code:
```
dccMarkdown("![](images/image.jpg)")
```

The image still does not render when I run app.R

**Comment by yuliaUU** [comment]
I wonder if you can try a picture in .png format? I think that maybe the issue

**Comment by firasm** [comment]
hi @jimmyliu1326 - sorry, I think I misunderstood the question as for `milestone04` rather than `assignment04`. The instructions above are for embedding an image into an Rmd file (for the screenshot of your dashboard proposal).

## Method 1: Using `htmlImg`

For including images in a Dash app, use the html component: `htmlImg`

Add this in the list of divs:

```
htmlImg(src='https://upload.wikimedia.org/wikipedia/commons/c/c5/En-wikipedia.jpg')
```

## Method 2: Using `dccMarkdown`

Add an image just like you would in markdown.

```
dccMarkdown("![](https://upload.wikimedia.org/wikipedia/commons/c/c5/En-wikipedia.jpg)")
```

It's a little trickier to add a local image, so it's actually better and more robust if you add the image via a URL - this is sufficient for Assignment 4.

@STAT547-UBC-2019-20/students : see above clarification on adding images in Dash Apps via URL for Assignment 4.

**Comment by yuliaUU** [comment]
I managed the `dccMarkdown("![](url to image .png)")` work, it just can be done to only some of the images available online

**Comment by jimmyliu1326** [comment]
Great, specifying image urls did the trick! I tried both .png and .jpg images and they both seem to work. Thanks!

**Comment by carleenaortega** [comment]
I did both methods (htmlImg and dccMarkdown) to add an image in the list of divs but it doesn't work for me.
![Screen Shot 2020-03-23 at 11 07 59 AM](https://user-images.githubusercontent.com/54973786/77348368-907bab80-6cf6-11ea-9cc6-83f008df5387.png)

**Comment by firasm** [comment]
Was there an error message? Can you post the image URL as code here too (rather than as a screenshot)?

**Comment by yuliaUU** [comment]
@carleenaortega  can you copy a link here so I can try

**Comment by carleenaortega** [comment]
here's the link @yuliaUU: https://github.com/STAT547-UBC-2019-20/assignment-04-carleenaortega/blob/master/app.R

**Comment by yuliaUU** [comment]
@carleenaortega 
I am checking your way of doing it,
I wonder if this one will work:
if you replace it with 
```
``` {r}
# All defaults
include_graphics(img1_path)
` ``
```

**Comment by carleenaortega** [comment]
it wasn't allowing me to enter an r chunk so i just added "include_graphics(img1_path)" but it still did not work..

**Comment by yuliaUU** [comment]
@carleenaortega  link was wrong!
dccMarkdown("
      ![]   (https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/2002-08_Koi_in_pond.jpg/1280px-2002-08_Koi_in_pond.jpg)
                  ")

you need to press on the picture and right-click to choose copy image address, you copied url of the website, not image

Note: I added extra space between [] and () so you can see the code

worked for me!

**Comment by carleenaortega** [comment]
thanks! did the same thing and it worked!
