### ISSUE TITLE
Download guidebook as pdf?

### ISSUE THREAD

**Issue by mnybe1** [STAT547-UBC-2019-20/Discussions#46]
Hey Firas, just tried to download the class notes/guidebook from https://stat545guidebook.netlify.com/ as a pdf so I can access some class material when I don't have internet, but the download link on the top toolbar doesn't seem to work. Would it be possible to make this download-able? 
Thanks

**Comment by firasm** [comment]
Hmm - I didn't even know that existed. I have had bad experiences converting Rmd files to PDFs as it warps all the formatting of the code chunks and tables. I'll try to look into it if I get a chance this weekend.

In the meantime, the guidebook is actually a GitHub repo [here](https://github.com/STAT545-UBC/Classroom) so I encourage you to clone it on your computer just so you at least have the Rmd files that you can individually knit in case you don't have internet.

Let me know if you run into any troubles!

**Comment by mnybe1** [comment]
Ok cool, thanks!
