### ISSUE TITLE
dccSlider acting weird

### ISSUE THREAD

**Issue by SaelinB** [STAT547-UBC-2019-20/Discussions#47]
Hi, 

I'm trying to insert a slider into app.R, and keep getting this message even when I copy simple online examples: 
Invalid argument 'marks' passed into Slider.
Expected an object.
Was supplied type 'array'.

To see what was happening, I made new script and pasted the exact code from [here](https://dashr.plot.ly/getting-started) (last chunk at the bottom with slider), and it ran fine, even when the same slider code didn't work in my app.R 

After inspecting some things, I realized that this error message pops up *only* when debug=TRUE in app$run_server()  - even when I stop the script and re-start it, not just when updating. Taking this out, it's fine. 

Is this a weird bug? I found a [forum](https://www.dash.org/forum/threads/problem-with-range-slider-when-updating-dash-from-0-39-to-0-43-still-works-in-0-39.45876/) talking about people getting this error when they updated dash...

**Comment by dy-lin** [comment]
I had a similar issue-- I was able to get around it by assigning `marks` to a named list like here:
```
library(dashCoreComponents)
dccSlider(
    min=0,
    max=10,
    marks = list(
    "0" = "0 °F",
    "3" = "3 °F",
    "5" = "5 °F",
    "7.65" = "7.65 °F",
    "10" = "10 °F"
    ),
    value=5
  )
```

The name corresponds to a numerical 'step' as a string.

> If slider marks are defined and step is set to NULL then the slider will only be able to select values that have been predefined by the marks. marks is a list where the keys represent the numerical values and the values represent their labels.

I took the above code and text snippet from the dccSlider [documentation](https://dashr.plot.ly/dash-core-components/slider).

**Comment by firasm** [comment]
Thanks @SaelinB for pointing this out, and for the workaround @dy-lin.

I have reported the bug to [dashR here as an issue](https://github.com/plotly/dashR/issues/187).

In the meantime, looks like you need to specify the marks as a list as above.

**Comment by almas2019** [comment]
Hi everyone,
I don't know if this is okay to post @firasm .:
If you are having trouble, Diana above mentioned creating a named list.  See here for this:
https://stackoverflow.com/questions/39059295/convert-list-to-named-list-in-r
Basically the steps are the names of the list and the labels are the list members.(in this case 3 is the name and "3 °F" is the list item.
