### ISSUE TITLE
how to submit Teamwork Document?

### ISSUE THREAD

**Issue by HJMcSorley** [STAT547-UBC-2019-20/Discussions#48]
Hello @firasm @yuliaUU 
How should we submit the [TeamWork Document](https://stat545.stat.ubc.ca/evaluation/teamwork/)?

Thanks!

**Comment by dy-lin** [comment]
I think you just submit it as you would assignment04 since it's in the assignment04 repository (i.e. it will be part of your tagged release)

**Comment by firasm** [comment]
Yep, I’ve included a template teamwork doc in the A4 repo so just update it in the repo and the right TA will find it.

**Comment by HJMcSorley** [comment]
Excellent! Thanks 👍
