### ISSUE TITLE
No YAML Header for cm102_participation.Rmd

### ISSUE THREAD

**Issue by hadleyd2** [STAT547-UBC-2019-20/Discussions#5]
Hello,

For the [second participation Rmd](https://github.com/STAT547-UBC-2019-20/Discussions/blob/master/participation/cm102/cm102_participation.Rmd), there is no YAML header. Was this excluded on purpose so that we add our own YAML header or is it still supposed to knit?

Thank you!

**Comment by firasm** [comment]
Nope, just an oversight! Good catch, thanks!

fixed in 4fe8542
