### ISSUE TITLE
EDA_script.R runs multiple times with makefile

### ISSUE THREAD

**Issue by SaelinB** [STAT547-UBC-2019-20/Discussions#50]
Hello, 

When running 'make all',  our makefile  runs each script once for each target of the script. For our EDA_script, we have 12 targets, so it runs 12 times. 

I tried specifying only 1 target of the EDA_script.R (as running once would make all of them anyways), but all of these 12 targets are then dependencies in our knit_final.R, and 'make all' gives an error that there is no rule to make these. 

Is there a way to make EDA_script run only once?

**Comment by firasm** [comment]
Hi @SaelinB and @carleenaortega : It looks like [this solution](https://github.com/STAT547-UBC-2019-20/Discussions/issues/39#issuecomment-601885850) from issue #39 by Matthew should fix your issue - have you tried it?

I have also tried it and can confirm this works.

<img width="1008" alt="Screen Shot 2020-03-21 at 11 10 29 PM" src="https://user-images.githubusercontent.com/2507459/77243604-33cea280-6bc9-11ea-8caf-b1bae980bea6.png">

Also, one other thing - it is generally advised not to make your `clean` target the first one, as if you type "make" in a command line, it will destructively delete files. I'd move that to the end.

Let me know if this doesn't work.

**Comment by SaelinB** [comment]
@firasm great that works, thank you!
