### ISSUE TITLE
graph components using ggplotly

### ISSUE THREAD

**Issue by mksm1228** [STAT547-UBC-2019-20/Discussions#51]
Hi @firasm,

For assignment 4, one of the tasks is to add 2 graph components using the ggplotly objects we created. It's a dumb question, but is this task asking us to simply add color, theme, titles etc using ggplot2?

**Comment by firasm** [comment]
oh - no, that's not what is intended. Simpler than that:

A ggplotly object is input into a dccGraph component --> this is one component. You have to do this twice (so two plots, and two components):

> - Using `ggplot`, create a histogram of the diamond price on the x-axis and number of diamonds on the y-axis.
> - Using `ggplot`, create a second plot (of your choice)

**Comment by mksm1228** [comment]
Oh, thanks, I am overthinking things. Thanks!
