### ISSUE TITLE
`continent_colours` in app.R

### ISSUE THREAD

**Issue by firasm** [STAT547-UBC-2019-20/Discussions#53]
hey @STAT547-UBC-2019-20/students,

To answer the question a few people had about where `continent_colors` came from in this ggplot code:

```
  # make the plot
  p <- ggplot(data, aes(x=year, y=!!sym(yaxis), colour=continent)) +
    geom_line() +
    scale_color_manual(name="Continent", values=continent_colors) +
    scale_x_continuous(breaks = unique(data$year))+
    xlab("Year") +
    ylab(y_label) +
    ggtitle(paste0("Change in ", y_label, " Over Time: ", 
                   country_select)) +
    theme_bw()
  
  ggplotly(p)
```

The vector `continent_colors` is actually something that gets loaded in when you load the `gapminder` dataset.

See below:
![Screen Shot 2020-03-24 at 2 43 30 PM](https://user-images.githubusercontent.com/2507459/77479870-d8293280-6ddd-11ea-8466-506e4d1d9d55.png)

Sorry if this seemed a bit mysterious when I used it out of the blue in our app today.

**Comment by dy-lin** [comment]
There doesn't seem to be a significant difference if you omit `scale_color_manual(name="Continent", values=continent_colors)` since `colour=continent` is already an `aes` in `ggplot()`. Does the extra `scale_color_manual` just pick the specific colours to those in `continent_colors`?

**Comment by firasm** [comment]
Yep those hex codes above encode each continent to a particular colour. For e.g., `#7f3b08` [is a medium dark shade of orange](https://encycolorpedia.com/7f3b08).

Documentation [here](https://ggplot2.tidyverse.org/reference/scale_manual.html)
