### ISSUE TITLE
corrplot & plotly

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#55]
@firasm, is there an easy/straightforward way to convert a `corrplot` plot into a `ggplot` so that I can use `ggplotly()`? Would using a package like `ggcorrplot` work?

**Comment by firasm** [comment]
Hmmm good question! It would depend if the object that is being used is a ggplot object or a baseR object (or something else. If it's a ggplot object, it *should* work, but I'll be honest and say I haven't tested it.

If you can give me a minimal working example, I can give it a go and see if I can get it to work?

Another option of course, is to do a correlation plot using straight ggplot like [here](correlation plot in ggplot). I will admit, that the `ggcorrplot` and `corrplot` packages produce much more customizable visualizations.

If it doesn't work, the default/backup option should be just to use a static image... but this is lame and no one wants that.

P.S. (another option is to use Plotly to create the correlation plot)

**Comment by dy-lin** [comment]
Thank you! It ended up working for `ggcorrplot`, just for some reason doesn't work when `method = "circle"` (only works for `method = "square"`).
