### ISSUE TITLE
Reminder about assignments

### ISSUE THREAD

**Issue by yuliaUU** [STAT547-UBC-2019-20/Discussions#56]
Just want to remind couple things about your assignments:
- unless specified, you always submit an URL to **tag release**
- if you are working with `Rmd` file, don't forget to knit it to viewable format: such as `pdf`/ `md`/ `html`
- If you provide `html` , please make it viewable and post a link in README file 

Here are instructions on how to do that on our website: https://stat545.stat.ubc.ca/evaluation/assignments/

**Comment by HJMcSorley** [comment]
Is it correct that the lowest of our assignment grades will be dropped?

**Comment by yuliaUU** [comment]
yep!! correct!

**Comment by HJMcSorley** [comment]
Great! Thanks!
