### ISSUE TITLE
reset button

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#59]
How do you write the function in an `app$callback` so that a property of a component is reset/changed?

In my case, I was able to write the callbacks to reset all graphs to their default values using a `dccButton`, however, I see that all dropdown menus/radio items are still at their last 'user set' option. How do I reset those values back to the default as well?

```
corr_label <- daqBooleanSwitch(id = 'label_toggle',
                               on = FALSE,
                               label = 'Label Toggle:',
                               labelPosition = "top")

reset <- htmlButton("Reset", id = 'reset_button', n_clicks = 0)
```

```
app$callback(
  output = list(id = 'label_toggle', property = 'on'),
  params = list(input(id = 'reset_button', property='n_clicks')),
  function(clicks) {
    if (clicks > 0 ) {
      # reset the label_toggle property 'on' = FALSE (the default)
    }
  }
)
```

The issue I'm facing is that, after a reset, if another component like a dropdown menu was chosen from, the `label_toggle` remains `on` and still is considered `on` after the user selects something else from the dropdown menu despite the fact that the graphs have been reset (since the toggle itself was not reset).

**Comment by firasm** [comment]
Here's an example I hacked together, try this - does this help you get most of the way there?

You will need to either set up multiple callbacks or have a callback with multiple outputs.

```
library(dash)
library(dashDaq)
library(dashHtmlComponents)

app <- Dash$new()

app$layout(htmlDiv(list(
	daqBooleanSwitch(id = "my-boolean-switch",
									 on = FALSE),
	htmlButton("Resets", id="reset-button", n_clicks=0),
	htmlDiv(id = "boolean-switch-output")
)))

app$callback(
	output(id = "boolean-switch-output", property = "children"),
	params = list(input(id = "my-boolean-switch", property = "on")),
	
	update_booleanswitch <- function(on) {
		return (sprintf("The switch is %s.", on))
	}
)

app$callback(
	output(id = "my-boolean-switch", property = "on"),
	params = list(input(id = "reset-button", property = 'n_clicks')),
	reset_btn <- function(val){
		val = FALSE
	}
)

app$run_server(debug=TRUE)
```

**Comment by dy-lin** [comment]
How does the function for `update_booleanswitch` work if I do not want to print any message to screen?

EDIT: Nevermind, I see now! I'll try updating other components and let you know how it goes.

**Comment by dy-lin** [comment]
@firasm, the reset button works to reset all the graphs and other buttons/dropdowns. I am now having the issue that since the other call backs use n_clicks > 0 as whether or not to use default values, that after pressing the reset button once, it will always satisfy that condition. For example, here is an example callback:

```
### Callback to update the correlation plot
app$callback(
  output = list(id = 'corr', property = 'figure'),
  params = list(input(id = 'layout_button', property='value'),
                input(id = 'diagonal_toggle', property = 'on'),
                input(id = 'viridis_button', property='on'),
                input(id = 'label_toggle', property='on'),
                input(id = 'themes', property='value'),
                input(id = 'reset_button', property = 'n_clicks')),
  function(layout, diag, viridis,label,theme, clicks) {
    if (clicks > 0 ) {
      make_cor_plot()
    } else {
    make_cor_plot(layout,diag,viridis,label, theme)
    }
  }
)
```

How do I make it so **after** the reset button is used to execute this call back that the reset button's n_clicks is set back to 0?

Are there such things as ordered/nested/conditional callbacks?
