### ISSUE TITLE
Question about Assignment 5 Task 1.1

### ISSUE THREAD

**Issue by hadleyd2** [STAT547-UBC-2019-20/Discussions#61]
Hello,

I am not sure what the second bullet point in [Assignment 5 Task 1.1](https://stat545.stat.ubc.ca/evaluation/assignment_05/assignment_05/) is asking for. Text is repeated below:

> make sure to add a line with annottaion to a slider explaining what the options mean (you can use htmlP() to add this)

In Assignment 4, we created a dropdown menu and a slider. Is this bullet point asking us to explain the options of the slider only? Should we mention that it is not affecting the histogram since we have not been told to link the slider to the histogram? I have already labelled my slider and the options are labelled, so I feel it is self-explanatory. Any annotation that I add will simply restate the title and option names in sentence form which seems to be redundant. Can someone please elaborate on what is expected here?

Thanks!
-Dan

**Comment by yuliaUU** [comment]
Hi,

I am sorry my instructions was not clear. I meant that before the slider there will be some text describing what slider do , e.g. choose the diamond' cut or select the variable of interest

You will need to do it for both dropdown and slider , cause at the end you will connect both of them. If you feel that the components you designed are self explanatory,  you don't have to do it!

Does it make sense? I will review instructions tomorrow to make it more clear!

**Comment by hadleyd2** [comment]
Hello @yuliaUU,

Thanks for responding so quickly! I think I understand. We basically just need to label the dropdown and sliders with some description of what they do.

Why do you recommend `htmlP()` while the guidebook has been using `htmlLabel()`? Should I switch to using `htmlP()`?

Thanks!

**Comment by yuliaUU** [comment]
Yes, you are right label would be a better option, I just provided suggestion that we already used in class so that people who are not familiar with the new items could achieve the goal easier. But I will update assignment to include `htmlLabel` as it would be the best option in this case. Thank you for your feedback! 
It is very helpful!

**Comment by firasm** [comment]
This was based before too so I'll just provide a more comprehensive answer. The html components are listed [here and described in more detail](https://dash.plotly.com/dash-html-components/p). 

Both components will (probably) work but `htmlLabel` is more appropriate, especially if the description is short.

See examples in action of what `p` and `label` do (in the HTML world, where they come from):

<img width="1062" alt="Screen Shot 2020-03-28 at 12 34 38 AM" src="https://user-images.githubusercontent.com/2507459/77817988-311df280-708c-11ea-8c73-a671df04d08b.png">

<img width="1038" alt="Screen Shot 2020-03-28 at 12 38 56 AM" src="https://user-images.githubusercontent.com/2507459/77818034-8954f480-708c-11ea-881a-3b30f1074849.png">

**Comment by almas2019** [comment]
I'm a bit confused with the instructions here, so for the histogram we were plotting by price, when we link our dropdown, does the dropdown mean we are now plotting by clarity or are we still plotting by price but filtered by clarity?

**Comment by firasm** [comment]
Does this answer your question @hadleyd2 ? if so, please close :-)

**Comment by hadleyd2** [comment]
Thanks for the help, everyone!
