### ISSUE TITLE
Error loading data locally

### ISSUE THREAD

**Issue by mnybe1** [STAT547-UBC-2019-20/Discussions#63]
Hi, I'm receiving this error message when running '_make all_' or '_Rscript scripts/load_data.R --data_url="https://raw.githubusercontent.com/hanrach/youtube_dataset/master/CAvideos.csv"_ 'locally, so I'm not able to get the data for our project:

Attempting to download data and write to disk...
error object is Error in file(file, ifelse(append, "a", "w")): cannot open the connection

Data has been downloaded successfully!
Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/Users/marionnyberg/Google Drive/BC/UBC/STAT547/group_2_youtube/data/youtube_data.csv': No such file or directory

Is there an easy fix for this? 
Thanks

**Comment by yuliaUU** [comment]
I think you suppose d to put your data in the public folder. ( remember where we put raw data). I think because your folder is private, that creates an issue

can you share the code it is running?

Firas, correct me if I am wrong

**Comment by firasm** [comment]
Yep @mnybe1 - you should put your datasets in this repo that I created (and gave you access to): https://github.com/STAT547-UBC-2019-20/data_sets

Then you can grab the public link for it and use it for your scripts.

**Comment by hanrach** [comment]
The Makefile uses the url from a public repository:
https://raw.githubusercontent.com/hanrach/youtube_dataset/master/CAvideos.csv

and local path is not hardcoded anywhere...

**Comment by firasm** [comment]
Okay, I'm [cloning your repo](https://github.com/STAT547-UBC-2019-20/group_2_youtube) and taking a look.

**Comment by firasm** [comment]
Ah solved it! 

Your `load_data.R` script requires a `data` folder to be present in the repo. That folder isn't there, so even though the data is downloaded, it can't find anywhere to put it.

You have two options:

1) In your `load_data` script, check if the folder exists and create it if not. [Here](https://stackoverflow.com/a/29784923) is an example of how to do that.

2) create the `data` folder in your repo 

Here's the success message

```
here() starts at /Users/firasm/tmp/group_2_youtube
Attempting to download data and write to disk...
Data has been downloaded successfully!
```

**Comment by hanrach** [comment]
Thank you!   
An issue we ran into in github is that it does not allow us to add empty directories, so I think that's why we had this problem.

**Comment by firasm** [comment]
Right - one workaround is to add a README.md in that file ; that can never hurt (you should also avoid deleting ALL files in the directory, perhaps do `rm data/*.csv` rather than `rm data/*` in your Makefile).

Feel free to close the issue when it's done

**Comment by mnybe1** [comment]
Great, thanks so much, all working now!
