### ISSUE TITLE
Problems with dash after R update

### ISSUE THREAD

**Issue by SaelinB** [STAT547-UBC-2019-20/Discussions#65]
Hello,
I just updated to R 3.6.3, and I re-installed dash with `install_github(plotly/dashR, upgrade = TRUE)` with no problems. I can load dashCoreComponents and dashHtmlComponents, but when I try to run app.R it says:

_package ‘dashCoreComponents’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
Execution halted_

When I try `install.packages("dashCoreComponents")` it says: 

_package ‘dashCoreComponents’ is not available (for R version 3.6.3)_

Is there anything anyone suggests doing?  Thanks!

**Comment by firasm** [comment]
hmm - that's weird. 

Things I would try: 

- check version of R running in the terminal/command-line. Is it different from 3.6.3? Type `R` in a command line and then check version by `sessionInfo()`

- Restart RStudio

- uninstall dashr `remove.packages()` 

- Restart Rstudio

- reinstall dashr (`install_github("plotly/dashR", upgrade=TRUE)`)

**Comment by yuliaUU** [comment]
Can you try and update the package?

**Comment by SaelinB** [comment]
I tried all the above, and I've tried removing dash, dashCoreComponents and dashHtmlComponents separately before reinstalling dashr, and my command line version is 3.6.3. I've tried updating dash, as well as html/core components separately. I get the same errors. Is it possible that it doesn't work with this version?

**Comment by firasm** [comment]
I just updated to 3.6.3 on my other laptop (boy was it a huge pain) - and after about 20 mins of re-installing I can confirm that dash does indeed work with R 3.6.3

**Comment by firasm** [comment]
Oh also, I just noticed that you're tying to use `install.packages` to install dash core components.

That won't work as you need to install it using 

`install_github("plotly/dashR", upgrade=TRUE)`

That should take care of installing dash core components and dash html components. 

Let's hop on a zoom call at some point tomorrow to troubleshoot. I think this is happening because you have some package version errors. I'm surprised the `install_github` command doesn't fix it...

**Comment by dy-lin** [comment]
I'm on macOS Catalina and didn't have issues with R 3.6.3 and dashR. Maybe it has something to do with Windows/Linux OS?

**Comment by SaelinB** [comment]
Yeah, I have ubuntu so it could have something to do with that? But yes @firasm let's call tomorrow

**Comment by firasm** [comment]
Okay, let's do 1 PM tomorrow?

I'm available anytime until 3...

### Zoom details

Firas Moosvi is inviting you to a scheduled Zoom meeting.

Topic: Dash Troubleshooting
Time: Mar 30, 2020 01:00 PM Vancouver

Join Zoom Meeting
https://ubc.zoom.us/j/662327208

Meeting ID: 662 327 208

One tap mobile
+16473744685,,662327208# Canada

**Comment by SaelinB** [comment]
Yep that works, see you then!

**Comment by firasm** [comment]
Ah! We were supposed to put it in Renviron!

See [older issue about this here](https://github.com/STAT547-UBC-2019-20/Discussions/issues/52#issuecomment-603020871)

let me know if it works!

**Comment by firasm** [comment]
Hey @SaelinB did this get fixed?

**Comment by SaelinB** [comment]
Sorry, was busy with other things and just did it now, works great!! Thanks for your help :)

**Comment by firasm** [comment]
Nice!
