### ISSUE TITLE
Scale of x-axis (date format) in ggplotly unmatches the line graph

### ISSUE THREAD

**Issue by qiyangqd** [STAT547-UBC-2019-20/Discussions#66]
Hi! I've plotted a line graph using `ggplot2()`, and its x-axis is in date format ("2012-01-01"). The graph looks good, but when I put it into `ggplotly()`, the label on the x-axis doesn't match the value of x in the line graph. It seems `ggplotly()` has changed something. It'll be great if you could help me with this! Thanks a lot in advance!

Below are the screenshots showing my problem:
- This is the right figure in `ggplot2()`
![image](https://user-images.githubusercontent.com/54858649/77938378-81eb4200-726a-11ea-9a5c-1e317b68c6b3.png)

- These are the wrong figures in `ggplotly()`: The range of the date on the line graph (2010-01-02, 2014-12-31) doesn't macth the scale of x-axis (2008, somewhere earlier than 2014). 
![image](https://user-images.githubusercontent.com/54858649/77938464-9c252000-726a-11ea-86e1-abb2783fd00d.png)
![image](https://user-images.githubusercontent.com/54858649/77938474-a0513d80-726a-11ea-9bd5-4b234915193d.png)

The script I'm using is as follows (coverted to .txt so there won't be so many codes in the issue):
[bug.txt](https://github.com/STAT547-UBC-2019-20/Discussions/files/4404244/bug.txt)

**Comment by firasm** [comment]
wow this looks like a serious bug! Good catch!

I'll have to dig into it a bit more - thanks for the sample code to reproduce this!

In the meantime, you probably shouldn't spend too much more time on debugging this (assuming you've tried the basic things of checking your data to make sure it looks ok).

**Comment by firasm** [comment]
Found a similar issue here, just on a whim can you try [this solution](https://stackoverflow.com/a/45086926) ?

**Comment by qiyangqd** [comment]
Hi @firasm ! Thank you for showing me the solution! I'm sorry I tried but it didn't change to the right one as expected. I used it like this:

a <- ggplot(df_year_change) +
  geom_line(aes(x= **as.POSIXct(date)**, y=pm2.5),
            alpha = 0.6,
            size = 0.6) +
  geom_vline(xintercept = as.numeric(as.Date("2013-09-01")),
             linetype=4, color = "blue", size = 1) +
  labs(x = "Time",
       y = "[pm2.5]",
       title = "[pm2.5] VS Time") +
  theme_classic()     _# I deleted the line `scale_x_date()` in my original bug.R code, since it gives an error if using `as.POSIXct()`_
ggplotly(a)

**Comment by yuliaUU** [comment]
`scale_x_date(date_labels = "%Y",limits = as.Date(c("2010-01-02","2014-12-31")))` will solve everything, I used a code from `bug.txt`

your date axis was not plottling dates correctly, you specified format "%Y-%m-%d", but axis showed years only, so you have to tell ggplot the format of date to display

**Comment by qiyangqd** [comment]
Wow thanks @yuliaUU ! I tried your suggestion and just used another format "%Y-%m-%d" (as I want keep its date), and it worked!

**Comment by yuliaUU** [comment]
%Y% will change the date format, only in x-axis labels s ( you can use "%b-%Y" ,
 you can put any format you like there, it will not change the values from your dataset. unless you want x-axis to have days, month and years ( then you need "%Y-%m-%d" )

**Comment by qiyangqd** [comment]
Ohh I see! The values are not changed, just the label of the x-axis. Yes, I would like the x-axis to have day, month and year so users can track down to a specific date. Thank you very much for the clarification! I'll close the issue soon.

**Comment by yuliaUU** [comment]
No worries! glad the issue is solved!

**Comment by firasm** [comment]
Nice work both!
