### ISSUE TITLE
Lagging Tabs

### ISSUE THREAD

**Issue by almas2019** [STAT547-UBC-2019-20/Discussions#67]
Hi all,
I did the tab layout for the assignment but I noticed quite a bit of lag when updating between tabs (it works but its slow). Is there a way to speed this up or is it because of the 2 graphs on the second tab?

**Comment by yuliaUU** [comment]
I read that it is plotly that’s taking the bulk of the load time. I wonder how you set up your graphs:
- ggplotly() are inside the functions OR
-  dccGraph( id="",  figure=ggplotly()) )

 I wonder if playing around with this can speed up the process?

**Comment by yuliaUU** [comment]
also, having multiple callbacks can reduce the app loading time. try to combine as many callbacks as possible.

**Comment by yuliaUU** [comment]
Found the following from [here](https://www.r-bloggers.com/speeding-up-r-plotly-web-apps-r-x-javascript-part-i/):
`The number of graphs you plot or the type of graphs you use does not affect the bundle size – the whole plotly package is loaded. So this means that even though we are only using bar and line charts, the scripts for drawing maps, 3D graphs, heatmaps etc. are all being loaded.`

```
ggplotly(graph) %>%
  partial_bundle()
```
this reduced the time for my app.R significantly ( but still not super fast)
