### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#68]
Hi @firasm,

@Nima-Jamshidi and I were put in the same break room and did not receive feedback on our dashboard from our peers. We tried to reach out to you but you were in another break room and could not see our messages, even after we sent the message using the main session.

What should we do for our participation/feedback issue?

**Comment by firasm** [comment]
sorted out [here](https://github.com/STAT547-UBC-2019-20/group_01_dlin_njamshidi/issues/50).

My apologies for this!
