### ISSUE TITLE
Update the deployed app

### ISSUE THREAD

**Issue by luckymeng7** [STAT547-UBC-2019-20/Discussions#70]
Hi @firasm ,

What are the proper steps to update the app after we deployed it? Should we clone the updated repo again and repeat the creating container or other steps again? It's a bit painful to re-deploy everything all over again when I find out there are some missing packages to be installed.

Thanks,
Monica

**Comment by yuliaUU** [comment]
I think you just hit deploy app again

**Comment by luckymeng7** [comment]
Ok, so the 20 mins deploying time could not be avoided?

**Comment by firasm** [comment]
Correct - that's why it's important not to "debug" on the server. 

You should have a fully functional app locally, and then as a final step, deploy it. You may run into some issues still and that's fine, but it's not a good idea to make changes, deploy, get an error, fix etc...

**Comment by luckymeng7** [comment]
Any tips on how to check if I've all the packages installed in init.R?

**Comment by firasm** [comment]
Yep - but nothing magical or fast: Go through your app, and make a list of all the packages you use (`library('blah')`) and then make sure the `init.R` file contains all those packages.

If you were diligent about keeping your README updated, then your list of package dependencies there should help!

**Comment by luckymeng7** [comment]
Gotcha, will include every detail for the packages. Thanks @firasm and @yuliaUU
