### ISSUE TITLE
cm110 participation

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#71]
Is anyone else also finding that their `app.R` in cm110 doesn't work if `debug = TRUE`? I seem to see the same issue when using the `app_complete.R` from the Discussion repo (with my own `dash_components.R` and `dash_functions.R`)

**Comment by firasm** [comment]
yes unfortunately this seems to be a bug in Dash - [I reported here](https://github.com/plotly/dashR/issues/187).

Either the debug mode is overzealously complaining (bug), or there is a problem that I cannot see.
