### ISSUE TITLE
assignment 6

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#72]
I vaguely remember in the class meeting that assignment 6 has been released but I can't seem to find the link on the assignments [page](https://stat545.stat.ubc.ca/evaluation/assignments/).

**Comment by evelynjulia** [comment]
It was meant to be released late yesterday....

@firasm could you release the assignment soon so that we can get started on it?

**Comment by firasm** [comment]
Sorry folks. 

I’m waiting for permission to use someone else’s app in the assignment... just waiting for confirmation. 

By tonight it should be there one way or another. I’ll adjust due date by 24 hours to compensate. 

Apologies for the delay!

**Comment by firasm** [comment]
A6 now posted here: https://stat545.stat.ubc.ca/evaluation/assignment_06/assignment_06/

I have added 24h to the due date.

**Comment by dy-lin** [comment]
Hi @firasm @yuliaUU, A6 extended deadline does not look reflected on the Canvas submission link?

**Comment by yuliaUU** [comment]
let me check!

**Comment by yuliaUU** [comment]
@dy-lin I see it is available until April 7th 6pm, 24 hr more than usual

**Comment by dy-lin** [comment]
I thought normally, the assignments/milestones were due Saturday night at 6pm, with a 48h grace period: Monday night at 6pm.

However since moving to Zoom/online classes, everything was given an additional 24h grace period to Tuesday night at 6pm.

And with the additional 24h for **assignment 6**, shouldn't it be available until Wednesday night at 6pm (April 8th, 6pm)?

Right now I see it is set as April 7, 6pm (the same as milestone06), even though A6 should have 24 h more than milestone6?

**Comment by firasm** [comment]
I think it was mistakenly reverted to the regular schedule. 

It's now due on Sunday + 72h again.
