### ISSUE TITLE
Teamwork doc missing

### ISSUE THREAD

**Issue by evelynjulia** [STAT547-UBC-2019-20/Discussions#73]
I don't think the assignment 6 teamwork doc is in the repo...

**Comment by firasm** [comment]
Rats! you're right .

Sorry about that, you can grab it from [here](https://github.com/STAT547-UBC-2019-20/Discussions/blob/master/teamwork.Rmd) and add it to the repo.

**Comment by firasm** [comment]
Ok I added it to everyone's repos!  should be good now.

Thanks @evelynjulia
