### ISSUE TITLE
Assignment 06 task 3 mapproj?

### ISSUE THREAD

**Issue by mksm1228** [STAT547-UBC-2019-20/Discussions#74]
Hello @firasm,

For task 3 of assignment 06, the heroku app will not deploy and when I type in heroku log --tail in the terminal, one of the errors that pops is that mapproj does not exist. However, mapproj is a package and I had installed it prior to ensure the Boston crime app.R would work. Is there a work around for this issue? I also have all 5 files (dockerfile, init.R, app.json, heroku.yml, apt-packages) in the repo. I forked the assignment repo to the downloads folder on my computer, essentially followed the guidebook.

**Comment by yuliaUU** [comment]
did you modify init.R? to include the libraries you need to download?

**Comment by firasm** [comment]
Give us a link to your repo and we can have a look.

**Comment by mksm1228** [comment]
@yuliaUU @firasm 

Yulia's suggestion of adding install.packages('mapproj') to the init.R file worked! Thanks Yulia!

**Comment by yuliaUU** [comment]
Great it helped!don't forget, some of those 5 files you included have to be modified to match your project!

**Comment by mksm1228** [comment]
Ok thanks for the note!
