### ISSUE TITLE
Assignment 6 bug

### ISSUE THREAD

**Issue by hanrach** [STAT547-UBC-2019-20/Discussions#76]
When I fix the five bugs and run Rscript app.R  with `app$run_server(host = "0.0.0.0", port = Sys.getenv('PORT', 8050), debug= TRUE)` there is an error saying:

```
Fire started at 0.0.0.0:8050
start: 0.0.0.0:8050
error: cannot coerce type 'environment' to vector of type 'list'

```

I'm not sure what's going on here, I don't think any of the bugs are related to using `list`.

**Comment by yuliaUU** [comment]
`debug=FALSE` , will it work?

**Comment by yuliaUU** [comment]
also, just curious, will this one work for you?
`app$run_server(host = '127.0.0.1', ports = Sys.getenv('PORT', 8050))`

**Comment by hanrach** [comment]
@yuliaUU , thanks for replying!

Setting debug= FALSE still gives me the same error with more text

```
Fire started at 0.0.0.0:8050
start: 0.0.0.0:8050
request: 127.0.0.1 - ID_127.0.0.1 [05/Apr/2020:17:44:13 -0700] "GET / HTTP/1.1" 200 670 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
error: cannot coerce type 'environment' to vector of type 'list'
request: 127.0.0.1 - ID_127.0.0.1 [05/Apr/2020:17:44:14 -0700] "GET /_dash-layout HTTP/1.1" 500 0 "http://0.0.0.0:8050/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
request: 127.0.0.1 - ID_127.0.0.1 [05/Apr/2020:17:44:14 -0700] "GET /_dash-dependencies HTTP/1.1" 200 162 "http://0.0.0.0:8050/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
request: 127.0.0.1 - ID_127.0.0.1 [05/Apr/2020:17:44:14 -0700] "GET /favicon.ico HTTP/1.1" 200 670"http://0.0.0.0:8050/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML,like Gecko) Chrome/80.0.3987.163 Safari/537.36"
```
and  same with `app$run_server(host = '127.0.0.1', ports = Sys.getenv('PORT', 8050))`. The problem I don't think lies with the `app$run_server`, because it's saying it cannot coerce type environment to list. And the page loaded says `error loading layout`. Perhaps there is a bug in the layout?

**Comment by yuliaUU** [comment]
can you give me a link to your app? I will try and check what is wrong!

**Comment by hanrach** [comment]
Thank you!

https://github.com/STAT547-UBC-2019-20/assignment-06-hanrach/blob/master/app.R

**Comment by yuliaUU** [comment]
```
function(year_value, neighbourhood_value, crime_value) {
    make_choropleth(df, gdf, year_value, neighbourhood_value, crime_value)
  })
```

I think the issue is in callbacks:
df and gdf are not the input from any slider or dropdown, and df / gdf are not assigned any default values inside the function too.

I would write it like this: 
```
function(year_value, neighbourhood_value, crime_value) {
    make_choropleth(year_value, neighbourhood_value, crime_value)
  })
```
and then produce  df and gdf inside the function

**Comment by jimmyliu1326** [comment]
Having the exact same issues here, tried the above solutions, still producing the same errors. The page just displays ```error loading layout``` when I open up 127.0.0.1 in my browser.

**Comment by hanrach** [comment]
In my case, it turned out that I did not really solve the bug. How I debugged was to comment out everything except plotting functions and included graph one by one in app$layout.

**Comment by jimmyliu1326** [comment]
Ah, yah was able to narrow it down to graph2 component, it turned out that I never properly fixed the bug in ```trendplot()```. Thanks! :D

**Comment by firasm** [comment]
Great - nice work folks! 

I hope this assignment was useful! You often learn a lot about new frameworks when debugging others' code.
