### ISSUE TITLE
Milestone 06: Procfile

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#77]
On the [milestone6](https://stat545.stat.ubc.ca/evaluation/milestone_06/milestone_06/) criteria page:

> As part of this task, in addition to a correctly deployed app, we will also check the following files: 
> - `Procfile`
> - `app.json`
> - `heroku.yml`
> - `init.R`
> - `Dockerfile`

What is a `Procfile`? Does it serve the same purpose as the `apt-packages` file? The `cm111` example [repository](https://github.com/STAT547-UBC-2019-20/dashR_heroku_deploy) does **NOT** have a `Procfile` either?

**Comment by firasm** [comment]
Ah - that is a remnant from an older version of the instructions. Now it's called `apt-packages`.

Good catch, thanks. I've fixed it and pushing the update now.

**Comment by firasm** [comment]
Updated ! should be up soon.
