### ISSUE TITLE
Submitting participation assignment?

### ISSUE THREAD

**Issue by stannam** [STAT547-UBC-2019-20/Discussions#79]
Hi.
I'm just wondering how to submit the participation assessment. Do I need to submit a URL to the release (as we did for the project milestones or assignment)? But there is no way I can submit one via canvas. Do we just leave the repository as we did for STAT545 so that TAs can grade it after the deadline?

**Comment by firasm** [comment]
Thanks @stannam - we have a canvas assignment ready where you can submit the link but it isn't open yet.

@yuliaUU or I will open it soon. Thanks!

F

**Comment by yuliaUU** [comment]
@stannam , I opened the link!

**Comment by stannam** [comment]
Thanks for your response. I've submitted the link to a release. 
Thanks!
