### ISSUE TITLE
Teamwork canvas assignment

### ISSUE THREAD

**Issue by evelynjulia** [STAT547-UBC-2019-20/Discussions#80]
What do we submit for this? I thought we handed in the teamwork docs with our assignments. Do we have to submit something else on Canvas?

**Comment by yuliaUU** [comment]
[Teamwork Document](https://stat545.stat.ubc.ca/evaluation/teamwork/)
Due: March 21 (for parameterized report project) and April 4 2020 (for dashboard project).

**Comment by firasm** [comment]
Nothing, there is no submission needed for this. It’s for internal (book-keeping) use only

We will review the two teamwork docs you submitted and assign you a value in that canvas assessment so it shows up correctly in your Grades page.
