### ISSUE TITLE
issue with plotly map

### ISSUE THREAD

**Issue by mksm1228** [STAT547-UBC-2019-20/Discussions#83]
Hello @firasm @yuliaUU 

@Sihaoyu1220  and I have an issue with the plotly scattermapbox where the points on the map will disappear or reappear when we switch the tabs. We tested it out with our friends and for some friends it will work fine (the points will stay), others it will not, seems to be completely random. Could you please see our code and let us know what might we be doing wrong? We feel that the dashboard is very close to completion except for this one minor bug in the Map tab. 

https://github.com/STAT547-UBC-2019-20/group_3_mksm1228_sihaoyu1220

Best,
Martin

**Comment by firasm** [comment]
Is it deployed already? can you provide a link to the deployed version?

**Comment by mksm1228** [comment]
https://group3-airbnb2.herokuapp.com/ 

Thanks Firas!

**Comment by firasm** [comment]
I can reproduce the problem in Chrome on macOS (sometimes) but not on Safari.

here is the Javascript Error console (in Chrome View, Developer console).

I see errors like this: `Error: <path> attribute d: Expected number, "Mundefined,506.86…".`

Does this mean anything to you? Hopefully it points you in the right direction. Perhaps there's a problem in the data

![Screen Shot 2020-04-06 at 6 32 42 PM](https://user-images.githubusercontent.com/2507459/78620498-04f53500-7835-11ea-9c56-177b58010121.png)

**Comment by mksm1228** [comment]
Hey Firas,

Thanks for looking into the issue. We have never seen an error like that before and Google doesnt show anything. Would it be fine to submit this as it is currently? If you select something, the map works properly, but it just doesn't load properly when you first click the Map tab.

**Comment by firasm** [comment]
Yes sounds fine. Just add an issue in your repo filing this as a bug/future enhancement.
