### ISSUE TITLE
Grace period also apply to participation?

### ISSUE THREAD

**Issue by qiyangqd** [STAT547-UBC-2019-20/Discussions#86]
Hi! Sorry for the last-minute question! I just want to make sure if the grace period also applies to the participation. Does it mean we can submit a link the participation release to canvas on Apr 13 before 6 pm (as it's indicated in canvas now) and will not lose marks for the delay? Thanks a lot!

**Comment by yuliaUU** [comment]
@qiyangqd yes, that is correct!

**Comment by qiyangqd** [comment]
Awesome! Thanks @yuliaUU !
