### ISSUE TITLE
participation

### ISSUE THREAD

**Issue by hanrach** [STAT547-UBC-2019-20/Discussions#87]
Is there a grace period for participation hand in?

**Comment by firasm** [comment]
yes, same grace period.

**Comment by hanrach** [comment]
Is it the 72 hour grace period? On canvas it says it's available until April 13th 6pm.

**Comment by yuliaUU** [comment]
yes, that deadline already include 72 hr grace period, so you need to submit before 6pm today

**Comment by firasm** [comment]
I mean, we can extend it if absolutely necessary but ideally you should submit them by today so we can complete grading for the course.

**Comment by hanrach** [comment]
I thought the grace period of 72 hrs would make it due on the 14th... given that the original due date was on the 11th.

**Comment by firasm** [comment]
I have changed the availability period on Canvas to reflect 72h from when it's due.

**Comment by hanrach** [comment]
Thanks!
